server:
  port: ${PORT:8761}

message: Spring Cloud Config EurekaServer

spring:
  application:
    name: eurekaServer

eureka:
  instance:
    hostname: eureka-server 
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 
