server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: Gateway

  cloud:    
    gateway:      
      discovery:
        locator:
          enabled: true
      routes:
        - id: userRoute
          uri: lb://UserApi     
          predicates:
            - Path=/users/**
        - id: bookListsRoute
          uri: lb://BookApi   
          predicates:
            - Path=/book-lists/**
        - id: diaryRoute
          uri: lb://BookApi
          predicates:
            - Path=/diary/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"

  main:
    allow-bean-definition-overriding: true

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      exposure:
        include: gateway,health,info
  endpoint:
    gateway:
      enabled: true
